version: '3'

services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - 8089:80
    volumes:
      - type: bind
        source: .
        target: /var/www/html
      - type: bind
        source: ./resources/docker/site.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - laravel

  php:
    build:
      context: ./resources/docker
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '33066:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    volumes:
      - db:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    ports:
      - '63791:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db:
    driver: local
