window.pluploadL10n = {
  'queue_limit_exceeded': 'You have attempted to queue too many files.',
  'file_exceeds_size_limit': '%s exceeds the maximum upload size for this site.',
  'zero_byte_file': 'This file is empty. Please try another.',
  'invalid_filetype': 'Sorry, this file type is not permitted for security reasons.',
  'not_an_image': 'This file is not an image. Please try another.',
  'image_memory_exceeded': 'Memory exceeded. Please try another smaller file.',
  'image_dimensions_exceeded': 'This is larger than the maximum size. Please try another.',
  'default_error': 'An error occurred in the upload. Please try again later.',
  'missing_upload_url': 'There was a configuration error. Please contact the server administrator.',
  'upload_limit_exceeded': 'You may only upload 1 file.',
  'http_error': 'HTTP error.',
  'upload_failed': 'Upload failed.',
  'big_upload_failed': 'Please try uploading this file with the %1$sbrowser uploader%2$s.',
  'big_upload_queued': '%s exceeds the maximum upload size for the multi-file uploader when used in your browser.',
  'io_error': 'IO error.',
  'security_error': 'Security error.',
  'file_cancelled': 'File canceled.',
  'upload_stopped': 'Upload stopped.',
  'dismiss': 'Dismiss',
  'crunching': 'Crunching\u2026',
  'deleted': 'moved to the trash.',
  'error_uploading': '\u201c%s\u201d has failed to upload.',
}

window._wpMediaModelsL10n = {
  'settings': {
    'ajaxurl': '/dashboard/resource/media',
    'post': { 'id': 0 },
  },
}

window._wpPluploadSettings = {
  'defaults': {
    'file_data_name': 'file',
    'url': '/dashboard/resource/media',
    'filters': {
      'max_file_size': '134217728b',
      'mime_types': [{ 'extensions': 'svg,jpg,jpeg,jpe,gif,png,bmp,tiff,tif,ico,asf,asx,wmv,wmx,wm,avi,divx,flv,mov,qt,mpeg,mpg,mpe,mp4,m4v,ogv,webm,mkv,3gp,3gpp,3g2,3gp2,txt,asc,c,cc,h,srt,csv,tsv,ics,rtx,css,htm,html,vtt,dfxp,mp3,m4a,m4b,aac,ra,ram,wav,ogg,oga,flac,mid,midi,wma,wax,mka,rtf,js,pdf,class,tar,zip,gz,gzip,rar,7z,psd,xcf,doc,pot,pps,ppt,wri,xla,xls,xlt,xlw,mdb,mpp,docx,docm,dotx,dotm,xlsx,xlsm,xlsb,xltx,xltm,xlam,pptx,pptm,ppsx,ppsm,potx,potm,ppam,sldx,sldm,onetoc,onetoc2,onetmp,onepkg,oxps,xps,odt,odp,ods,odg,odc,odb,odf,wp,wpd,key,numbers,pages' }],
    },
    'multipart_params': {
      '_token': $('meta[name="csrf_token"]').attr('content'),
    },
  }, 'browser': { 'mobile': false, 'supported': true }, 'limitExceeded': false,
}

window._wpMediaViewsL10n = {
  'url': 'URL',
  'addMedia': 'Add Media',
  'search': 'Search',
  'select': 'Select',
  'cancel': 'Cancel',
  'update': 'Update',
  'replace': 'Replace',
  'remove': 'Remove',
  'back': 'Back',
  'selected': '%d selected',
  'dragInfo': 'Drag and drop to reorder media files.',
  'uploadFilesTitle': 'Upload Files',
  'uploadImagesTitle': 'Upload Images',
  'mediaLibraryTitle': 'Media Library',
  'insertMediaTitle': 'Add Media',
  'createNewGallery': 'Create a new gallery',
  'createNewPlaylist': 'Create a new playlist',
  'createNewVideoPlaylist': 'Create a new video playlist',
  'returnToLibrary': '\u2190 Return to library',
  'allMediaItems': 'All media items',
  'allDates': 'All dates',
  'noItemsFound': 'No items found.',
  'insertIntoPost': 'Insert into post',
  'unattached': 'Unattached',
  'mine': 'Mine',
  'trash': 'Trash',
  'uploadedToThisPost': 'Uploaded to this post',
  'warnDelete': 'You are about to permanently delete this item from your site.\nThis action cannot be undone.\n \'Cancel\' to stop, \'OK\' to delete.',
  'warnBulkDelete': 'You are about to permanently delete these items from your site.\nThis action cannot be undone.\n \'Cancel\' to stop, \'OK\' to delete.',
  'warnBulkTrash': 'You are about to trash these items.\n  \'Cancel\' to stop, \'OK\' to delete.',
  'bulkSelect': 'Bulk Select',
  'trashSelected': 'Move to Trash',
  'restoreSelected': 'Restore from Trash',
  'deletePermanently': 'Delete Permanently',
  'apply': 'Apply',
  'filterByDate': 'Filter by date',
  'filterByType': 'Filter by type',
  'searchMediaLabel': 'Search Media',
  'searchMediaPlaceholder': 'Search media items...',
  'noMedia': 'No media files found.',
  'attachmentDetails': 'Attachment Details',
  'insertFromUrlTitle': 'Insert from URL',
  'setFeaturedImageTitle': 'Featured Image',
  'setFeaturedImage': 'Set featured image',
  'createGalleryTitle': 'Create Gallery',
  'editGalleryTitle': 'Edit Gallery',
  'cancelGalleryTitle': '\u2190 Cancel Gallery',
  'insertGallery': 'Insert gallery',
  'updateGallery': 'Update gallery',
  'addToGallery': 'Add to gallery',
  'addToGalleryTitle': 'Add to Gallery',
  'reverseOrder': 'Reverse order',
  'imageDetailsTitle': 'Image Details',
  'imageReplaceTitle': 'Replace Image',
  'imageDetailsCancel': 'Cancel Edit',
  'editImage': 'Edit Image',
  'chooseImage': 'Choose Image',
  'selectAndCrop': 'Select and Crop',
  'skipCropping': 'Skip Cropping',
  'cropImage': 'Crop Image',
  'cropYourImage': 'Crop your image',
  'cropping': 'Cropping\u2026',
  'suggestedDimensions': 'Suggested image dimensions: %1$s by %2$s pixels.',
  'cropError': 'There has been an error cropping your image.',
  'audioDetailsTitle': 'Audio Details',
  'audioReplaceTitle': 'Replace Audio',
  'audioAddSourceTitle': 'Add Audio Source',
  'audioDetailsCancel': 'Cancel Edit',
  'videoDetailsTitle': 'Video Details',
  'videoReplaceTitle': 'Replace Video',
  'videoAddSourceTitle': 'Add Video Source',
  'videoDetailsCancel': 'Cancel Edit',
  'videoSelectPosterImageTitle': 'Select Poster Image',
  'videoAddTrackTitle': 'Add Subtitles',
  'playlistDragInfo': 'Drag and drop to reorder tracks.',
  'createPlaylistTitle': 'Create Audio Playlist',
  'editPlaylistTitle': 'Edit Audio Playlist',
  'cancelPlaylistTitle': '\u2190 Cancel Audio Playlist',
  'insertPlaylist': 'Insert audio playlist',
  'updatePlaylist': 'Update audio playlist',
  'addToPlaylist': 'Add to audio playlist',
  'addToPlaylistTitle': 'Add to Audio Playlist',
  'videoPlaylistDragInfo': 'Drag and drop to reorder videos.',
  'createVideoPlaylistTitle': 'Create Video Playlist',
  'editVideoPlaylistTitle': 'Edit Video Playlist',
  'cancelVideoPlaylistTitle': '\u2190 Cancel Video Playlist',
  'insertVideoPlaylist': 'Insert video playlist',
  'updateVideoPlaylist': 'Update video playlist',
  'addToVideoPlaylist': 'Add to video playlist',
  'addToVideoPlaylistTitle': 'Add to Video Playlist',
  'attachmentsList': 'Attachments list',
  'settings': {
    'tabs': [],
    'tabUrl': '',
    'mimeTypes': { 'image': 'Images', 'audio': 'Audio', 'video': 'Video' },
    'captions': true,
    'nonce': { 'sendToEditor': '9604871f71' },
    'post': {},
    'defaultProps': { 'link': 'none', 'align': '', 'size': '' },
    'attachmentCounts': { 'audio': 1, 'video': 1 },
    // 'oEmbedProxyUrl': '',
    'embedExts': [
      'mp3',
      'ogg',
      'flac',
      'm4a',
      'wav',
      'mp4',
      'm4v',
      'webm',
      'ogv',
      'flv'],
    'embedMimes': {
      'mp3': 'audio\/mpeg',
      'ogg': 'audio\/ogg',
      'flac': 'audio\/flac',
      'm4a': 'audio\/mpeg',
      'wav': 'audio\/wav',
      'mp4': 'video\/mp4',
      'm4v': 'video\/mp4',
      'webm': 'video\/webm',
      'ogv': 'video\/ogg',
      'flv': 'video\/x-flv',
    },
    'contentWidth': 980,
    'months': [],
    'mediaTrash': 0,
  },
}

window.getUserSetting = function (key, _default) {
  var data = JSON.parse(localStorage.getItem('__user_settings')) || {}
  return data.hasOwnProperty(key) ? data[key] : _default
}

window.setUserSetting = function (key, value, _del) {
  var data = JSON.parse(localStorage.getItem('__user_settings')) || {}

  if (_del) {
    data[key] = null
  } else {
    data[key] = value
  }

  localStorage.setItem('__user_settings', JSON.stringify(data))
}
